spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:9010/db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  ai:
    openai:
      api-key: sk-your
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-5.2-codex
          temperature: 0.0

jwt:
  secret-key: nfsfnwufbwrh38hrnwjfnwekfn3ou2f

stripe:
  api:
    secret:
  webhook:
    secret: whsec_130fa616de516e5ad291ec1e9bd8dac5008dad21daff078ae5ed3ae052967195

client:
  url: http://localhost:8080

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects